### PR TITLE
Added PLSQL implementation

### PR DESCRIPTION
**Pull request by jgebal**
I've made the Kata going through TDD lifecycle of Reg-Green-Refactor
The cycle is documented by commits
If you find it useful then go ahead and merge ;)
Cheers

### CODE REVIEW

**Comment by froderik** [comment]
Nice - will merge!

**Comment by froderik** [comment]
Would be cool if you could add the hook script so that it can be run from the test script in root.

**Comment by jgebal** [comment]
Hi Fredrik
I can do that as an extra exercise, however there are quite few quite
difficult requirements like:
- having Oracle DB in place
- having Oracle client
It would be great to have chef script for entire setup, but still you'll
need to download some gigabytes from the web
What do you think?

2015-05-04 12:23 GMT+01:00 Fredrik Rubensson <notifications@github.com>:

**Comment by froderik** [comment]
Yeah - maybe not worth it.... :-) Maybe a line or two in the readme about how to set it up would be enough!

**Comment by jgebal** [comment]
Will do a blog post on this exercise today and will put a link into readme,
that should give some light.

2015-05-04 14:24 GMT+01:00 Fredrik Rubensson <notifications@github.com>:

**Comment by froderik** [comment]
great!

**Pull request merged**
